language: perl
sudo: true

os:
  - osx
  - linux

before_install:
  #- if [ "$TRAVIS_OS_NAME" == "linux" ] ; then sudo apt-get -qq update ; fi
  #- if [ "$TRAVIS_OS_NAME" == "linux" ] ; then sudo apt-get install libxtst-dev ; fi

install:
  - cpanm -n Dist::Zilla
  - ./maint/travis-install-mods
  - dzil authordeps --missing | cpanm -n
  - dzil listdeps   --missing | cpanm -n

perl:
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"

script:
  - dzil test -v

